name: ZAP_ALL

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  zap_scan1:
    runs-on: ubuntu-latest
    name: Perform Full URL scan
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Generating report skeletons
        if: success() || failure()
        run: |
          touch fullscan_report.html
          chmod a+w fullscan_report.html
          ls -lrt
      - name: Run ZAP FULL scan
        run: |
          set +e
          
          echo "Pulling ZAP image..."
          docker pull ghcr.io/zaproxy/zaproxy:stable -q
          echo "Starting ZAP Docker container..."
          docker run -v ${GITHUB_WORKSPACE}:/zap/wrk/:rw ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py -t https://managed-identity-wallets.dev.demo.catena-x.net -r fullscan_report.html -T 1
          
          echo "... done."
          
      - name: Upload HTML report
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: ZAP_FULL scan report
          path: ./fullscan_report.html
  

  zap_scan2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - name: Copy OpenAPI JSON
        run: cp .github/openapi_Knowledge_Agents.json $GITHUB_WORKSPACE

      - name: Check for API Key
        id: api-key
        run: |
          API_KEY=$(jq -r '.security[0].apiKey' $GITHUB_WORKSPACE/openapi_Knowledge_Agents.json)
          echo "API_KEY=$API_KEY" >> $GITHUB_ENV
          
      - name: Create ZAP Config File
        run: echo "api.port=9090" > $GITHUB_WORKSPACE/zap.conf
      - name: Verify ZAP Config File
        run: cat $GITHUB_WORKSPACE/zap.conf

      - name: Generating report skeletons
        if: success() || failure()
        run: |
          touch API_report.html
          chmod a+w API_report.html
          ls -lrt
          
      - name: Run ZAP API scan
        run: |
          set +e
          
          echo "Pulling ZAP image..."
          docker pull ghcr.io/zaproxy/zaproxy:stable -q
          echo "Starting ZAP Docker container..."
          docker run -v ${GITHUB_WORKSPACE}:/zap/wrk/:rw ghcr.io/zaproxy/zaproxy:stable zap-api-scan.py -t https://managed-identity-wallets.dev.demo.catena-x.net -f openapi -r API_report.html -T 1
          
          echo "... done."
          # Use the combined output as needed
          echo "Combined Output: $COMBINED_OUTPUT"
          
      - name: Upload HTML report
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: ZAP_API scan report
          path: ./API_report.html
