name: Nuclei - Vulnerability Scan and API Authentication Test

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  nuclei-scan-and-auth-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Nuclei - Vulnerability Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          target: https://knowledge.dev.demo.catena-x.net/conforming-agent/bind

      - name: API Authentication Test
        run: |
          # Perform API authentication testing using curl
          # Replace the placeholder URLs with the actual API endpoints
          curl -X GET https://knowledge.dev.demo.catena-x.net/conforming-agent/bind --header "Authorization: Basic ${{ secrets.BASIC_AUTH_TOKEN }}"
          curl -X GET https://knowledge.dev.demo.catena-x.net/conforming-agent/bind --header "X-Api-Key: ${{ secrets.API_KEY }}"
          curl -X GET https://knowledge.dev.demo.catena-x.net/conforming-agent/bind --header "Authorization: Bearer ${{ secrets.OUTH2 }}"

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nuclei.log
          path: nuclei.log

      - name: GitHub Security Dashboard Alerts update
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: nuclei.sarif
