name: ZAP API test
on:
  push:
    branches:
      - main

jobs:
  zap_full_scan:
    runs-on: ubuntu-latest
    name: OWASP ZAP-Fullscan
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Web Application Scan 
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://knowledge.dev.demo.catena-x.net'  # Please specify the target URL to be scanned
        
