name: ZAP API test
on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: API Test 1
        run: |
          response=$(curl -w "%{http_code}" -v -X GET https://knowledge.dev.demo.catena-x.net --user "${{ secrets.BASIC_AUTH_USER }}:${{ secrets.BASIC_AUTH_PASSWORD }}")
          echo "Response: $response"

          # Extract the HTTP status code
          http_status_code=$(echo "$response" | tail -c 4)
          echo "HTTP Status Code: $http_status_code"

          if [[ $http_status_code -ne 200 ]]; then
            echo "Error: HTTP request failed with status code $http_status_code"
            exit 1
          fi

          if [[ $response == *"authentication failure"* ]]; then
            echo "Authentication failure: Incorrect password for the user."
            exit 1
          fi


      - name: API Test 2
        run: |
          response=$(curl -X GET https://knowledge.dev.demo.catena-x.net/conforming-agent/bind --header "Authorization: Basic ${{ secrets.BASIC_AUTH_TOKEN }}")
          echo "Response: $response"
          
           # Extract the HTTP status code
          http_status_code=$(echo "$response" | tail -c 4)
          echo "HTTP Status Code: $http_status_code"
          
          if [[ $response == *"authentication failure"* ]]; then
            echo "Authentication failure: Incorrect Basic Auth token."
            exit 1
          fi

      - name: API Test 3
        run: |
          response=$(curl -X GET https://knowledge.dev.demo.catena-x.net/conforming-agent/bind --header "X-Api-Key: ${{ secrets.API_KEY }}")
          echo "Response: $response"

           # Extract the HTTP status code
          http_status_code=$(echo "$response" | tail -c 4)
          echo "HTTP Status Code: $http_status_code"
          
          if [[ $response == *"authentication failure"* ]]; then
            echo "Authentication failure: Incorrect API key."
            exit 1
          fi

      - name: API Test 4
        run: |
          response=$(curl -X GET https://knowledge.dev.demo.catena-x.net/conforming-agent/bind --header "Authorization: Bearer ${{ secrets.OAUTH2 }}")
          echo "Response: $response"

           # Extract the HTTP status code
          http_status_code=$(echo "$response" | tail -c 4)
          echo "HTTP Status Code: $http_status_code"
          
          if [[ $response == *"authentication failure"* ]]; then
            echo "Authentication failure: Incorrect OAuth2 token."
            exit 1
          fi

      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          format: openapi
          target: 'https://www.zaproxy.org/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
