name: ZAP Scans

on: [push]

jobs:
  zap_scan1:
    runs-on: ubuntu-latest
    outputs:
      id: ${{ steps.zap_scan1.outputs.id }}
    steps:
      - name: ZAP Scan 1
        id: zap_scan1
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://knowledge.dev.demo.catena-x.net'  # Specify the target URL for scan 1
        env:
          ZAP_REPORT_DIR: ${{ github.workspace }}/zap-scan1-results
      - name: Save output variables
        run: echo "zap_scan1_results=$ID" >> $GITHUB_ENV

  zap_scan2:
    runs-on: ubuntu-latest
    outputs:
      id: ${{ steps.zap_scan2.outputs.id }}
    steps:
      - name: ZAP Scan 2
        id: zap_scan2
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://example.com'  # Specify the target URL for scan 2
        env:
          ZAP_REPORT_DIR: ${{ github.workspace }}/zap-scan2-results
      - name: Save output variables
        run: echo "zap_scan2_results=$ID" >> $GITHUB_ENV

  process_results:
    needs: [zap_scan1, zap_scan2]
    runs-on: ubuntu-latest
    steps:
      - name: Process Results
        run: |
          echo "Results of ZAP Scan 1: $zap_scan1_results"
          echo "Results of ZAP Scan 2: $zap_scan2_results"
          echo "Combined Results: $zap_scan1_results $zap_scan2_results" >> "$GITHUB_OUTPUT"
