name: ZAP2

on:
  push:
    branches:
      - main

jobs:
  zap_scan2:
    runs-on: ubuntu-latest
    name: OWASP ZAP 2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          
      - name: Check for API Key
        id: api-key
        run: |
          API_KEY=$(jq -r '.security[0].apiKey' $GITHUB_WORKSPACE/openapi_Knowledge_Agents.json)
          echo "API_KEY=$API_KEY" >> $GITHUB_ENV
          
      - name: Create ZAP Config File
        run: echo "api.port=9090" > $GITHUB_WORKSPACE/zap.conf
      - name: Verify ZAP Config File
        run: cat $GITHUB_WORKSPACE/zap.conf

      - name: ZAP Scan 2
        id: step2
        run: |
          docker run \
            -v $GITHUB_WORKSPACE/zap.conf:/zap/wrk/zap.conf \
            --network=host \
            -e ZAP_AUTH_HEADER \
            -e ZAP_AUTH_HEADER_VALUE \
            -e ZAP_AUTH_HEADER_SITE \
            ghcr.io/zaproxy/zaproxy:stable zap-api-scan.py \
              -t https://managed-identity-wallets.dev.demo.catena-x.net/ \
              -f openapi \
              -J /zap/wrk/report_json.json \
              -w /zap/wrk/report_md.md \
              -r /zap/wrk/report_html.html \
              -config $GITHUB_WORKSPACE/zap.conf
        env:
          OUTPUT2: ${{ toJson(steps.step2.outputs) }}
          OPENAPI_FILE: $GITHUB_WORKSPACE/openapi_Knowledge_Agents.json
          apikey: ${{ steps.api-key.outputs.API_KEY }}

      - name: Debug ZAP Scan Output
        run: echo "ZAP Scan 2 Output:$OUTPUT2"
