name: ZAP2

on:
  push:
    branches:
      - main

jobs:
  zap_scan2:
    runs-on: ubuntu-latest
    name: OWASP ZAP 2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          
      - name: Copy OpenAPI JSON
        run: cp .github/workflows/t-systems6-catena-x_knowledge_agents_sparql_endpoint_specification-1.10.15-resolved.json $GITHUB_WORKSPACE
  
      - name: ZAP Scan 2
        id: step2
        uses: zaproxy/action-api-scan@v0.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://knowledge.dev.demo.catena-x.net/conforming-agent/bind'
          additional_params: "-config api.key=${{ secrets.API_KEY }}"
