name: ZAP2

on:
  push:
    branches:
      - main

jobs:
  zap_scan2:
    runs-on: ubuntu-latest
    name: OWASP ZAP 2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: ZAP Scan 2
        id: step2
        uses: zaproxy/action-api-scan@v0.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          format: openapi
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: https://managed-identity-wallets.dev.demo.catena-x.net/

